name: simpa
# set explicit label for cuda version to avoid possible mismatch between pytorch-cuda & cuda-nvcc
channels:
  - pytorch
  - nvidia/label/cuda-11.7.1
  - conda-forge
  - defaults
dependencies:
# simpa needs python <3.11:
  - python==3.10
# simpa needs pytorch:
  - pytorch
  - pytorch-cuda
  - torchvision
  - torchaudio
# other simpa dependencies:
  - matplotlib
  - numpy
  - scipy
  - pynrrd
  - scikit-image
  - xmltodict
  - h5py
  - pandas
  - coverage
  - deprecated
  - python-dotenv
  - requests
  - wget
# simpa dependencies not on conda-forge:
#  - pacfish
#  - jdata
# nvcc to compile mcx:
  - cuda-libraries-dev
  - cuda-nvcc
  - cuda-nvtx
  - cuda-cupti
# benchmarking dependencies
  - line_profiler
  - memory_profiler
